name: Capacitacion-Inbursa-2026

on:
  push:
    branches: [ "main", "python-insecure"]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      issues: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

  laboratorio_appPython:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      issues: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # =========================
      # SECRET SCANNING
      # =========================

      - name: Ejecutar Gitleaks
        shell: bash
        run: |
          docker run --rm \
            -v "$PWD:/repo" \
            ghcr.io/gitleaks/gitleaks:latest \
            detect \
            --source /repo \
            --report-format sarif \
            --report-path /repo/gitleaks-report.sarif \
            --no-git
        continue-on-error: true

      - name: Subir resultados de Gitleaks
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.sarif

      - name: Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-report.sarif
      # =========================
      # SAST – SEMGREP
      # =========================
      - name: Ejecutar Semgrep 
        run: |
          pip install semgrep
          semgrep --config p/python ./App --json > semgrep-report.json && semgrep --config p/python ./App --sarif > semgrep-report.sarif || true

      - name: Subir resultados de Semgrep 
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif

      # =========================
      # SCA – Trivy
      # =========================
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          scan-ref: ./App
          format: sarif
          output: trivy-SCA-report.sarif
        continue-on-error: true

      - name: Subir resultados de SCA con trivy
        uses: actions/upload-artifact@v4
        with:
          name: trivy-SCA-report.sarif
          path: trivy-SCA-report.sarif

      - name: Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-SCA-report.sarif
          category: trivy-fs

      # =========================
      # IMAGE SCAN – TRIVY
      # =========================
      - name: Build Docker image
        run: docker build -t app-image ./App

      - name: Ejecutar Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: image
          image-ref: app-image
          format: json
          output: trivy-report-ImagenContenedor.json
          ignore-unfixed: true
          timeout: 25m
        continue-on-error: true

      - name: Generar reportes SARIF de Trivy
        run: trivy image app-image --format sarif --output trivy-report-ImagenContenedor.sarif --ignore-unfixed --exit-code 0

      - name: Subir resultados de Trivy
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-ImagenContenedor
          path: trivy-report-ImagenContenedor.json

      - name: Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report-ImagenContenedor.sarif 
          category: trivy-image

      # =========================
      # IMAGE SCAN – CHECKOV
      # =========================
      - name: Ejecutar Checkov 
        run: |
          pip install -U checkov
          checkov -d ./App -o json -o sarif --output-file-path checkov-report.json,checkov.sarif --soft-fail

      - name: Upload Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: checkov-report.json

      - name: Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif


      # =========================
      # DAST – OWASP ZAP
      # =========================
      - name: Ejecutar OWASP ZAP
        run: |
          mkdir -p zap-results
          chmod 777 zap-results

          docker run -d --name app -p 5000:5000 app-image
          sleep 30

              docker run --rm \
              --network host \
              -v $(pwd)/zap-results:/zap/wrk \
              zaproxy/zap-stable \
              zap-baseline.py \
              -t http://localhost:5000 \
              -J zap-report.json \
              -I || true
          ls /zap/wrk

      - name: Subir resultados de OWASP ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-results/zap-report.json
      # =========================
      # POLICY AS CODE – OPA
      # =========================
      - name: Instalar OPA
        run: |
          sudo apt update
          sudo apt upgrade -y
          curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.70.0/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/opa
          opa version

      - name: Evaluar politicas
        run: |
          opa eval -i trivy-report-ImagenContenedor.json -d policy/trivy.rego 'data.policy.violation'
          opa eval -i checkov-report.json -d policy/checkov.rego 'data.policy.violation'
          opa eval -i semgrep-report.sarif -d policy/semgrep.rego 'data.semgrep.vulnerability_class'
          opa eval -i zap-results/zap-report.json -d policy/zap.rego 'data.alert_check.detected_alerts'